version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  describe:
    run: r:latest analysis/post-covid-metformin.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/age_pyramid_regions.png
      highly_sensitive:
        cohort: output/mydata.rds
